// Code generated by ifacemaker; DO NOT EDIT.

package ton

import (
	"context"

	"github.com/AnthonyHewins/tradovate"
	"google.golang.org/grpc"
)

// OrdersInterface ...
type OrdersInterface interface {
	CreateOCO(ctx context.Context, req *OcoReq, opts ...grpc.CallOption) (*tradovate.OcoResp, error)
	Create(ctx context.Context, req *CreateOrderReq, opts ...grpc.CallOption) (int64, error)
	CreateOSO(ctx context.Context, req *OsoReq, opts ...grpc.CallOption) (*tradovate.OsoResp, error)
}
